import 'dart:convert';
import 'dart:io';

import '../cores/core_registry.dart';
import '../models/core_manifest.dart';
import 'hash_verifier.dart';
import 'local_data_dir.dart';

/// Where on-demand core assets live — parsed from `cores/release.json`
/// (regenerated by `scripts/build_catalog.py`): the GitHub release tag
/// matching this build's pubspec version plus the asset file name for
/// every `delivery: download` core that has a pin for that platform.
///
/// This is the whole trust story (ADR-013): the app fetches exactly these
/// names, from exactly this tag, and verifies the bytes against the pin
/// that ships inside the same catalog it already trusts.
class CoreRelease {
  const CoreRelease({
    required this.repo,
    required this.tag,
    required this.assets,
  });

  /// `owner/name` of the repository whose releases host the core assets.
  final String repo;

  /// Release tag (e.g. `v0.2.0`) — pins in this build's catalog came from
  /// the same version.
  final String tag;

  /// platform-arch key -> core id -> asset file name.
  final Map<String, Map<String, String>> assets;

  factory CoreRelease.fromJson(Map<String, dynamic> json) {
    final assets = <String, Map<String, String>>{};
    final raw = json['assets'];
    if (raw is Map) {
      for (final entry in raw.entries) {
        final inner = <String, String>{};
        if (entry.value is Map) {
          entry.value.forEach((k, v) => inner[k.toString()] = v.toString());
        }
        assets[entry.key.toString()] = inner;
      }
    }
    return CoreRelease(
      repo: (json['repo'] as String?) ?? '',
      tag: (json['tag'] as String?) ?? '',
      assets: assets,
    );
  }

  /// Asset file name for [coreId] on [platformKey], or null when nothing
  /// is published for that pair (older catalogs, unbuilt platforms).
  String? assetName(String platformKey, String coreId) =>
      assets[platformKey]?[coreId];

  /// Full download URL for [coreId] on [platformKey].
  /// Throws [StateError] when no asset is published for that pair.
  Uri downloadUri(String platformKey, String coreId) {
    final name = assetName(platformKey, coreId);
    if (repo.isEmpty || tag.isEmpty || name == null) {
      throw StateError(
        '$coreId is not published for $platformKey yet (no release asset)',
      );
    }
    return Uri.parse(
      'https://github.com/$repo/releases/download/$tag/$name',
    );
  }
}

/// Streams one release asset as byte chunks. Implementations surface
/// transport/HTTP failures as errors on the stream (or synchronously).
abstract class CoreAssetFetcher {
  Stream<List<int>> open(Uri url);
}

/// Production fetcher: `dart:io` HTTP with redirect following — GitHub
/// release assets redirect to signed object-storage URLs. No extra
/// dependency; works on every platform that runs the app.
class HttpClientAssetFetcher implements CoreAssetFetcher {
  const HttpClientAssetFetcher();

  @override
  Stream<List<int>> open(Uri url) async* {
    final client = HttpClient()..autoUncompress = false;
    try {
      final request = await client.getUrl(url);
      final response = await request.close();
      if (response.statusCode != HttpStatus.ok) {
        throw StateError('HTTP ${response.statusCode} fetching $url');
      }
      yield* response;
    } finally {
      client.close(force: true);
    }
  }
}

/// Downloads a core on demand into the local vault, byte-verified.
///
/// Contract (nothing on the network is trusted):
/// 1. bytes stream into `<dest>.part` (memory-safe, size-capped);
/// 2. the part file is sha256-verified against the **manifest pin** —
///    the same pin the catalog already ships;
/// 3. only a verified file is renamed into place, with the `.ezpin`
///    sidecar the staging fast path expects;
/// 4. only then is the registry told to install.
///
/// Any failure deletes the partial file and throws a user-facing
/// [StateError]; the registry never learns about unverified bytes.
class CoreDownloader {
  CoreDownloader({
    required LocalDataDirProvider dirs,
    CoreAssetFetcher? fetcher,
    HashVerifier? hashes,
    bool Function()? isIOS,
  })  : _dirProvider = dirs,
        _fetcher = fetcher ?? const HttpClientAssetFetcher(),
        _hashes = hashes ?? const PlatformHashVerifier(),
        _isIOS = isIOS ?? _platformIsIOS;

  static bool _platformIsIOS() => Platform.isIOS;

  /// Refuse absurd payloads before hashing (largest shipped core ~170 MB).
  static const int maxAssetBytes = 512 * 1024 * 1024;

  final LocalDataDirProvider _dirProvider;
  final CoreAssetFetcher _fetcher;
  final HashVerifier _hashes;
  final bool Function() _isIOS;

  /// Fetches, verifies, stages, and installs one core.
  /// Returns the verified pin on success; throws [StateError] otherwise.
  Future<String> download({
    required CoreManifest manifest,
    required CoreRelease release,
    required String platformKey,
    required CoreRegistry registry,
  }) async {
    if (_isIOS()) {
      throw StateError('iOS never downloads cores (App Review 2.5.2/4.7)');
    }
    if (manifest.blocked) {
      throw StateError(
        '${manifest.name} is on hold: ${manifest.blockedReason}',
      );
    }
    final osKey = platformKey.split('-').first;
    if (manifest.delivery[osKey] != 'download') {
      throw StateError(
        '${manifest.id} is not a downloadable core on $osKey',
      );
    }
    final pin = manifest.artifacts[platformKey]?.toLowerCase();
    if (pin == null) {
      throw StateError(
        'No pinned artifact for ${manifest.id} on $platformKey',
      );
    }
    // Throws when nothing is published for this pair (honest UI message).
    final url = release.downloadUri(platformKey, manifest.id);

    final ext = platformKey.startsWith('windows')
        ? 'dll'
        : (platformKey.startsWith('macos') || platformKey.startsWith('ios'))
            ? 'dylib'
            : 'so';
    final dir = await _dirProvider.localDataDir();
    final coreDir = Directory('${dir.path}/cores/${manifest.id}');
    await coreDir.create(recursive: true);
    final dest = File('${coreDir.path}/${manifest.id}.$ext');
    final part = File('${dest.path}.part');
    if (part.existsSync()) {
      try {
        part.deleteSync();
      } catch (_) {}
    }

    var received = 0;
    final sink = part.openWrite();
    try {
      await for (final chunk in _fetcher.open(url)) {
        received += chunk.length;
        if (received > maxAssetBytes) {
          throw StateError(
            'Core asset larger than $maxAssetBytes bytes — refusing ${manifest.id}',
          );
        }
        sink.add(chunk);
      }
      await sink.flush();
      await sink.close();
    } catch (e) {
      try {
        await sink.close();
      } catch (_) {}
      try {
        if (part.existsSync()) part.deleteSync();
      } catch (_) {}
      if (e is StateError) rethrow;
      throw StateError('Download failed for ${manifest.id}: $e');
    }

    if (!await verifyPinnedFile(part.path, pin, hashes: _hashes)) {
      try {
        part.deleteSync();
      } catch (_) {}
      final stale = File('${part.path}.ezpin');
      if (stale.existsSync()) {
        try {
          stale.deleteSync();
        } catch (_) {}
      }
      throw StateError(
        'SHA-256 mismatch for ${manifest.id} — download discarded',
      );
    }

    if (dest.existsSync()) {
      try {
        dest.deleteSync();
      } catch (_) {}
      final old = File('${dest.path}.ezpin');
      if (old.existsSync()) {
        try {
          old.deleteSync();
        } catch (_) {}
      }
    }
    part.renameSync(dest.path);
    // Carry the verified sidecar across the rename (rename preserves
    // mtime/size, so its record still matches the destination).
    final partSidecar = File('${part.path}.ezpin');
    final destSidecar = File('${dest.path}.ezpin');
    if (partSidecar.existsSync()) {
      partSidecar.renameSync(destSidecar.path);
    } else {
      final stat = dest.statSync();
      destSidecar.writeAsStringSync(
        json.encode({
          'pin': pin,
          'size': stat.size,
          'mtimeMs': stat.modified.millisecondsSinceEpoch,
        }),
      );
    }

    registry.install(manifest, expectedSha256: pin);
    return pin;
  }
}
