// GENERATED by scripts/build_brand.py — do not edit by hand.
//
// The ezCORE mark and wordmark as Flutter paths: the same geometry as the
// SVG files in assets/branding/, so the app's logo matches them exactly.
// ignore_for_file: prefer_const_declarations

import 'dart:ui';

/// Mark box (logical units).
const double markWidth = 478.0;
const double markHeight = 200.0;

/// The cut between the two halves, where the blue light runs.
const Offset cutTop = Offset(179.0, 0.0);
const Offset cutBottom = Offset(299.0, 200.0);

/// Wordmark box: "ez CORE", baseline at [wordmarkHeight].
const double wordmarkWidth = 728.00;
const double wordmarkHeight = 100.0;

final List<Path> solidMarkPaths = [
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(9.00, 113.23)
    ..quadraticBezierTo(0.00, 100.00, 9.00, 86.77)
    ..lineTo(59.00, 13.23)
    ..quadraticBezierTo(68.00, 0.00, 84.00, 0.00)
    ..lineTo(151.00, 0.00)
    ..quadraticBezierTo(167.00, 0.00, 175.23, 13.72)
    ..lineTo(278.77, 186.28)
    ..quadraticBezierTo(287.00, 200.00, 271.00, 200.00)
    ..lineTo(84.00, 200.00)
    ..quadraticBezierTo(68.00, 200.00, 59.00, 186.77)
    ..close()
    ..moveTo(105.00, 60.00)
    ..quadraticBezierTo(105.00, 56.00, 109.00, 56.00)
    ..lineTo(131.00, 56.00)
    ..quadraticBezierTo(135.00, 56.00, 135.00, 60.00)
    ..lineTo(135.00, 81.00)
    ..quadraticBezierTo(135.00, 85.00, 139.00, 85.00)
    ..lineTo(160.00, 85.00)
    ..quadraticBezierTo(164.00, 85.00, 164.00, 89.00)
    ..lineTo(164.00, 111.00)
    ..quadraticBezierTo(164.00, 115.00, 160.00, 115.00)
    ..lineTo(139.00, 115.00)
    ..quadraticBezierTo(135.00, 115.00, 135.00, 119.00)
    ..lineTo(135.00, 140.00)
    ..quadraticBezierTo(135.00, 144.00, 131.00, 144.00)
    ..lineTo(109.00, 144.00)
    ..quadraticBezierTo(105.00, 144.00, 105.00, 140.00)
    ..lineTo(105.00, 119.00)
    ..quadraticBezierTo(105.00, 115.00, 101.00, 115.00)
    ..lineTo(80.00, 115.00)
    ..quadraticBezierTo(76.00, 115.00, 76.00, 111.00)
    ..lineTo(76.00, 89.00)
    ..quadraticBezierTo(76.00, 85.00, 80.00, 85.00)
    ..lineTo(101.00, 85.00)
    ..quadraticBezierTo(105.00, 85.00, 105.00, 81.00)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(469.00, 86.77)
    ..quadraticBezierTo(478.00, 100.00, 469.00, 113.23)
    ..lineTo(419.00, 186.77)
    ..quadraticBezierTo(410.00, 200.00, 394.00, 200.00)
    ..lineTo(327.00, 200.00)
    ..quadraticBezierTo(311.00, 200.00, 302.77, 186.28)
    ..lineTo(199.23, 13.72)
    ..quadraticBezierTo(191.00, 0.00, 207.00, 0.00)
    ..lineTo(394.00, 0.00)
    ..quadraticBezierTo(410.00, 0.00, 419.00, 13.23)
    ..close()
    ..moveTo(373.00, 72.00)
    ..arcToPoint(const Offset(343.00, 72.00), radius: const Radius.circular(15.00), largeArc: false, clockwise: true)
    ..arcToPoint(const Offset(373.00, 72.00), radius: const Radius.circular(15.00), largeArc: false, clockwise: true)
    ..close()
    ..moveTo(401.00, 100.00)
    ..arcToPoint(const Offset(371.00, 100.00), radius: const Radius.circular(15.00), largeArc: false, clockwise: true)
    ..arcToPoint(const Offset(401.00, 100.00), radius: const Radius.circular(15.00), largeArc: false, clockwise: true)
    ..close()
    ..moveTo(373.00, 128.00)
    ..arcToPoint(const Offset(343.00, 128.00), radius: const Radius.circular(15.00), largeArc: false, clockwise: true)
    ..arcToPoint(const Offset(373.00, 128.00), radius: const Radius.circular(15.00), largeArc: false, clockwise: true)
    ..close()
    ..moveTo(345.00, 100.00)
    ..arcToPoint(const Offset(315.00, 100.00), radius: const Radius.circular(15.00), largeArc: false, clockwise: true)
    ..arcToPoint(const Offset(345.00, 100.00), radius: const Radius.circular(15.00), largeArc: false, clockwise: true)
    ..close(),
];

final List<Path> wordmarkPaths = [
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(66.00, 67.00)
    ..arcToPoint(const Offset(59.00, 87.32), radius: const Radius.circular(33.00), largeArc: true, clockwise: false)
    ..lineTo(50.73, 80.85)
    ..arcToPoint(const Offset(55.50, 67.00), radius: const Radius.circular(22.50), largeArc: true, clockwise: true)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(9.50, 61.75)
    ..lineTo(66.00, 61.75)
    ..lineTo(66.00, 72.25)
    ..lineTo(9.50, 72.25)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(74.00, 35.50)
    ..quadraticBezierTo(74.00, 34.00, 75.50, 34.00)
    ..lineTo(128.50, 34.00)
    ..quadraticBezierTo(130.00, 34.00, 130.00, 35.50)
    ..lineTo(130.00, 43.00)
    ..quadraticBezierTo(130.00, 44.50, 128.98, 45.60)
    ..lineTo(89.02, 88.40)
    ..quadraticBezierTo(88.00, 89.50, 89.50, 89.50)
    ..lineTo(128.50, 89.50)
    ..quadraticBezierTo(130.00, 89.50, 130.00, 91.00)
    ..lineTo(130.00, 98.50)
    ..quadraticBezierTo(130.00, 100.00, 128.50, 100.00)
    ..lineTo(75.50, 100.00)
    ..quadraticBezierTo(74.00, 100.00, 74.00, 98.50)
    ..lineTo(74.00, 91.00)
    ..quadraticBezierTo(74.00, 89.50, 75.02, 88.40)
    ..lineTo(114.98, 45.60)
    ..quadraticBezierTo(116.00, 44.50, 114.50, 44.50)
    ..lineTo(75.50, 44.50)
    ..quadraticBezierTo(74.00, 44.50, 74.00, 43.00)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(286.00, 0.00)
    ..lineTo(204.00, 0.00)
    ..arcToPoint(const Offset(204.00, 100.00), radius: const Radius.circular(50.00), largeArc: false, clockwise: false)
    ..lineTo(286.00, 100.00)
    ..lineTo(286.00, 74.00)
    ..lineTo(204.00, 74.00)
    ..arcToPoint(const Offset(204.00, 26.00), radius: const Radius.circular(24.00), largeArc: false, clockwise: true)
    ..lineTo(286.00, 26.00)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(354.00, 0.00)
    ..lineTo(386.00, 0.00)
    ..arcToPoint(const Offset(386.00, 100.00), radius: const Radius.circular(50.00), largeArc: false, clockwise: true)
    ..lineTo(354.00, 100.00)
    ..arcToPoint(const Offset(354.00, 0.00), radius: const Radius.circular(50.00), largeArc: false, clockwise: true)
    ..close()
    ..moveTo(354.00, 26.00)
    ..lineTo(386.00, 26.00)
    ..arcToPoint(const Offset(386.00, 74.00), radius: const Radius.circular(24.00), largeArc: false, clockwise: true)
    ..lineTo(354.00, 74.00)
    ..arcToPoint(const Offset(354.00, 26.00), radius: const Radius.circular(24.00), largeArc: false, clockwise: true)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(454.00, 0.00)
    ..lineTo(480.00, 0.00)
    ..lineTo(480.00, 100.00)
    ..lineTo(454.00, 100.00)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(454.00, 0.00)
    ..lineTo(547.00, 0.00)
    ..arcToPoint(const Offset(547.00, 62.00), radius: const Radius.circular(31.00), largeArc: false, clockwise: true)
    ..lineTo(454.00, 62.00)
    ..close()
    ..moveTo(480.00, 24.00)
    ..lineTo(547.00, 24.00)
    ..arcToPoint(const Offset(547.00, 40.00), radius: const Radius.circular(8.00), largeArc: false, clockwise: true)
    ..lineTo(480.00, 40.00)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(514.00, 61.00)
    ..lineTo(542.00, 61.00)
    ..lineTo(578.00, 100.00)
    ..lineTo(550.00, 100.00)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(728.00, 0.00)
    ..lineTo(646.00, 0.00)
    ..arcToPoint(const Offset(646.00, 100.00), radius: const Radius.circular(50.00), largeArc: false, clockwise: false)
    ..lineTo(728.00, 100.00)
    ..lineTo(728.00, 74.00)
    ..lineTo(646.00, 74.00)
    ..arcToPoint(const Offset(646.00, 26.00), radius: const Radius.circular(24.00), largeArc: false, clockwise: true)
    ..lineTo(728.00, 26.00)
    ..close(),
  Path()
    ..fillType = PathFillType.evenOdd
    ..moveTo(620.00, 38.00)
    ..lineTo(714.00, 38.00)
    ..lineTo(714.00, 62.00)
    ..lineTo(620.00, 62.00)
    ..close(),
];
