import 'package:flutter/material.dart';

import 'brand_paths.g.dart';

/// The ezCORE mark: two halves of a gamepad and the blue light along the cut.
///
/// Painted from [solidMarkPaths], generated by scripts/build_brand.py from
/// the same shapes as assets/branding/mark.svg, so it matches the brand
/// files exactly and stays sharp at any size.
class BrandMark extends StatelessWidget {
  const BrandMark({
    super.key,
    this.height = 24,
    this.color = Colors.white,
    this.light = true,
  });

  final double height;
  final Color color;

  /// Draw the blue light along the cut.
  final bool light;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      label: 'ezCORE',
      child: SizedBox(
        width: height * markWidth / markHeight,
        height: height,
        child: CustomPaint(painter: _MarkPainter(color, light)),
      ),
    );
  }
}

/// "ez CORE" in the brand's lettering.
class BrandWordmark extends StatelessWidget {
  const BrandWordmark({super.key, this.height = 16, this.color = Colors.white});

  /// Height of the capitals.
  final double height;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: height * wordmarkWidth / wordmarkHeight,
      height: height,
      child: CustomPaint(painter: _WordmarkPainter(color)),
    );
  }
}

/// Mark and wordmark side by side, in the brand sheet's proportions.
class BrandLockup extends StatelessWidget {
  const BrandLockup({super.key, this.height = 28, this.color = Colors.white});

  /// Height of the mark.
  final double height;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      label: 'ezCORE',
      excludeSemantics: true,
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          BrandMark(height: height, color: color),
          SizedBox(width: height * 59 / markHeight),
          BrandWordmark(height: height * 0.63, color: color),
        ],
      ),
    );
  }
}

class _MarkPainter extends CustomPainter {
  _MarkPainter(this.color, this.light);

  final Color color;
  final bool light;

  @override
  void paint(Canvas canvas, Size size) {
    final k = size.height / markHeight;
    canvas.scale(k);
    final fill = Paint()..color = color;
    for (final p in solidMarkPaths) {
      canvas.drawPath(p, fill);
    }
    if (!light) return;
    final along = cutBottom - cutTop;
    final a = cutTop - along * 0.10;
    final b = cutBottom + along * 0.10;
    // The cut runs top-left to bottom-right, so a gradient across the
    // rectangle a→b runs along it: transparent ends, bright middle.
    Paint stroke(double width) => Paint()
      ..shader = const LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
        colors: [
          Color(0x00007BFF),
          Color(0xE6007BFF),
          Color(0xFF7DB9FF),
          Color(0xE6007BFF),
          Color(0x00007BFF),
        ],
        stops: [0, 0.35, 0.5, 0.65, 1],
      ).createShader(Rect.fromPoints(a, b))
      ..strokeWidth = width
      ..strokeCap = StrokeCap.round;
    canvas.drawLine(
      a,
      b,
      stroke(14)..maskFilter = MaskFilter.blur(BlurStyle.normal, 7),
    );
    canvas.drawLine(a, b, stroke(4));
  }

  @override
  bool shouldRepaint(_MarkPainter old) =>
      old.color != color || old.light != light;
}

class _WordmarkPainter extends CustomPainter {
  _WordmarkPainter(this.color);

  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.scale(size.height / wordmarkHeight);
    final fill = Paint()..color = color;
    for (final p in wordmarkPaths) {
      canvas.drawPath(p, fill);
    }
  }

  @override
  bool shouldRepaint(_WordmarkPainter old) => old.color != color;
}
